# Generated by Django 3.2 on 2021-04-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
